name: Hush                    # Workflow 이름
on:                               # Event 감지
  push:
    branches: [ master ]

jobs:                                # Job 설정
  build:
    runs-on: ubuntu-latest

    #strategy:
    #  matrix:
    #    node-version: [15.x]

    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v            # Node v 확인
        run: node -v

     #  - name: test    # test
     #    run: npm run test

      - name: Install Dependencies    # 의존 파일 설치
        run: npm install

      #- name: Build                   # Express Build
      #  run: npm run build

      - name: Deploy                  # deply to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }} # default : 22
          script: |
            cd /app/depromeet/ThreeMeals-back/ && git pull origin master
            npm run build
            /home/ubuntu/npm-global-modules/bin/pm2 restart ecosystem.config.js

